### PR TITLE
Add content-type application/json to authenticate request

### PR DESCRIPTION
**Pull request by jpbeaulieu**
Some api need to know the content-type in order to decode received data.

### CODE REVIEW

**Comment by jpbeaulieu** [comment]
Hi,

Would it be possible to release a new version after this pull request is completed?

That would be very appreciate.

Thanks a lot,

J.

**Comment by akagadovskiy** [comment]
The version was updated also for NPM.

**Comment by jpbeaulieu** [comment]
Could you please add a realese (tag) for the new version ?  So I can "bower update".  Thanks

**Comment by akagadovskiy** [comment]
Done. Thanks for contibution!

**Pull request merged**
